version: '3.8'

services:
  app:
    container_name: ai-editor
    # ✅ 这里的用户名改成了 qingyexshizhege
    image: qingyex/ai-image-editor:latest
    restart: always
    ports:
      - '5008:3008'
    # 读取同目录下的 .env 文件
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: ai-mongo
    restart: always
    # 数据库数据持久化到当前目录的 mongo-data 文件夹
    volumes:
      - ./mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
