import type { Metadata } from 'next';
import { cookies } from 'next/headers';

import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // 从 cookies 获取当前主题
  const cookieStore = await cookies();
  const theme = cookieStore.get('theme')?.value || 'light'; // 默认 'light'

  return (
    <html lang="en" data-theme={theme}>
      <body className="bg-background-light dark:bg-background-dark transition-colors! duration-500 min-h-screen">
        {children}
      </body>
    </html>
  );
}
